/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaztriqui;

import javax.swing.JFrame;

/**
 *
 * @author dylan
 */
public class interfaz extends javax.swing.JFrame {

    private String iniciarJuego = "X";
    boolean Cdisponible;
    
    
    public interfaz() {
        initComponents();
    }

    private void elegirJugador(){
        if(iniciarJuego.equalsIgnoreCase("X"))
        {
            iniciarJuego = "O";
        }
        else {
            iniciarJuego = "X";
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SI = new javax.swing.JButton();
        SC = new javax.swing.JButton();
        SD = new javax.swing.JButton();
        CI = new javax.swing.JButton();
        CC = new javax.swing.JButton();
        CD = new javax.swing.JButton();
        II = new javax.swing.JButton();
        IC = new javax.swing.JButton();
        ID = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        J1 = new javax.swing.JLabel();
        jlblJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        SI.setBackground(new java.awt.Color(204, 204, 204));
        SI.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIActionPerformed(evt);
            }
        });
        jPanel1.add(SI);

        SC.setBackground(new java.awt.Color(204, 204, 204));
        SC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCActionPerformed(evt);
            }
        });
        jPanel1.add(SC);

        SD.setBackground(new java.awt.Color(204, 204, 204));
        SD.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDActionPerformed(evt);
            }
        });
        jPanel1.add(SD);

        CI.setBackground(new java.awt.Color(204, 204, 204));
        CI.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIActionPerformed(evt);
            }
        });
        jPanel1.add(CI);

        CC.setBackground(new java.awt.Color(204, 204, 204));
        CC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        jPanel1.add(CC);

        CD.setBackground(new java.awt.Color(204, 204, 204));
        CD.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDActionPerformed(evt);
            }
        });
        jPanel1.add(CD);

        II.setBackground(new java.awt.Color(204, 204, 204));
        II.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        II.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        II.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IIActionPerformed(evt);
            }
        });
        jPanel1.add(II);

        IC.setBackground(new java.awt.Color(204, 204, 204));
        IC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        IC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        IC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICActionPerformed(evt);
            }
        });
        jPanel1.add(IC);

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout());

        J1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        J1.setText("    JUGADOR:");
        jPanel2.add(J1);

        jlblJugador.setBackground(new java.awt.Color(204, 204, 204));
        jlblJugador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblJugador.setOpaque(true);
        jPanel2.add(jlblJugador);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 360, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIActionPerformed
        if (SI.getText().equals("")){
            SI.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_SIActionPerformed

    private void SCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCActionPerformed
        if (SC.getText().equals("")){
        SC.setText(iniciarJuego);
        }
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_SCActionPerformed

    private void SDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDActionPerformed
        if (SD.getText().equals("")){
        SD.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_SDActionPerformed

    private void CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIActionPerformed
        if (CI.getText().equals("")){
        CI.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_CIActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        if (CC.getText().equals("")){
        CC.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_CCActionPerformed

    private void CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDActionPerformed
        if (CD.getText().equals("")){
        CD.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_CDActionPerformed

    private void IIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IIActionPerformed
        if (II.getText().equals("")){
        II.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_IIActionPerformed

    private void ICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICActionPerformed
        if (IC.getText().equals("")){
        IC.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_ICActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        if (ID.getText().equals("")){
        ID.setText(iniciarJuego);
        }
        
        
        if (iniciarJuego.equalsIgnoreCase("X"))
        {
          Cdisponible = false; 
        } else{
          Cdisponible = true; 
        }
        elegirJugador();
    }//GEN-LAST:event_IDActionPerformed
private JFrame frame;
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CC;
    private javax.swing.JButton CD;
    private javax.swing.JButton CI;
    private javax.swing.JButton IC;
    private javax.swing.JButton ID;
    private javax.swing.JButton II;
    private javax.swing.JLabel J1;
    private javax.swing.JButton SC;
    private javax.swing.JButton SD;
    private javax.swing.JButton SI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlblJugador;
    // End of variables declaration//GEN-END:variables
}
